name: 'MNE-Tools: Sync Dependencies to Environment File'
description: 'Sync dependency information from `pyproject.toml` to `environment.yml`.'
author: 'MNE-Tools'
inputs:
  project-root:
    description: 'The directory of the project to sync the dependency information for.'
    required: false
    default: ${{ github.workspace }}
  extras:
    description: >-
      Comma-separated names of extra dependencies in `pyproject.toml`'s
      `[project.optional-dependencies]` that should be included in
      `environment.yml`.
    required: false
    default: null
  additional-dependencies:
    description: >-
      Comma-separated names of additional dependencies that are not included in
      `pyproject.toml`, but which should be included in `environment.yml`.
    required: false
    default: null
  channels:
    description: 'Comma-separated names of channels to include in `environment.yml`.'
    required: false
    default: 'conda-forge'
  pip-dependencies:
    description: >-
      Comma-separated names of dependencies which should be installed via pip.
      The should be dependencies already included as core dependencies, in
      `extras`, or in `additional_dependencies`. Dependencies specified with
      extras or markers will be automatically included as pip dependencies.
    required: false
    default: null
  requirements-overrides:
    description: >-
      Comma-separated dependencies parseable by
      `packaging.requirements.Requirement`, which will override the information
      for those same dependencies as specified in `pyproject.toml`.
    required: false
    default: null
runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - name: Install actions dependencies
      run: |
        echo "ACTION_ROOT=$(dirname $(dirname ${{ github.action_path }}))" >> ${GITHUB_ENV}
        pip install ${{ env.ACTION_ROOT }}
      shell: bash
    - name: Sync dependencies to environment file
      working-directory: ${{ env.ACTION_ROOT }}
      run: |
        python sync_dependencies_to_environment_file.py \
          "${{ inputs.project-root }}" \
          --extras "${{ inputs.extras }}" \
          --additional_dependencies "${{ inputs.additional-dependencies }}" \
          --channels "${{ inputs.channels }}" \
          --pip_dependencies "${{ inputs.pip-dependencies }}" \
          --requirements_overrides "${{ inputs.requirements-overrides }}"
      shell: bash
