name: 'MNE-Tools: Check Qt import'
description: 'Check that a Qt binding is available in Python.'
author: 'MNE-Tools'
inputs:
  python-env-root:
    required: true
    description: 'The root directory of the Python environment prefix, such as a venv or conda environment.'
  qt-backend:
    required: true
    description: 'The Qt backend to check is importable (e.g., PySide6, PyQt6).'
runs:
  using: composite
  steps:
    - name: Add Python environment to PATH
      run: |
        echo "${{ inputs.python-env-root }}/bin" >> "$GITHUB_PATH"
      shell: bash
    - name: Get root directory of the action
      run: |
        action_path="${GITHUB_ACTION_PATH//\\//}"
        echo "ACTION_ROOT=$(dirname "$(dirname "$action_path")")" >> "$GITHUB_ENV"
      shell: bash
    - name: Check Qt import
      run: |
        ${{ env.ACTION_ROOT }}/tools/check_qt_import.sh ${{ inputs.qt-backend }}
      shell: bash
