name: Teams
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  sync_teams:
    name: Sync
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: sync-teams
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 2
      - name: Check for changes to teams.yaml
        id: teams_dirty
        run: |
          if ! $(git diff --quiet HEAD^ HEAD admin/teams.yaml); then
            echo "dirty=true" >> $GITHUB_OUTPUT
          fi
      - uses: scientific-python/sync-teams-action@main
        with:
          token: ${{ secrets.SYNC_TEAMS_TOKEN }}
          yamlpath: admin/teams.yaml
        if: steps.teams_dirty.outputs.dirty == 'true'
