name: Teams
on:
  push:
    branches:
      - main

jobs:
  sync_teams:
    name: Sync
    runs-on: ubuntu-latest
    environment:
      name: sync-teams
    steps:
      - name: Checkout teams list
        uses: actions/checkout@v3
        with:
          ref: main

      - uses: drammock/sync-teams-action@path
        with:
          token: ${{ secrets.SYNC_TEAMS_TOKEN }}
          yamlpath: admin/teams.yaml
